// _ServerSelector_EOArchive.java
// Generated by EnterpriseObjects palette at Tuesday, December 13, 2005 11:15:49 AM Asia/Taipei

import com.webobjects.eoapplication.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eointerface.*;
import com.webobjects.eointerface.swing.*;
import com.webobjects.eointerface.swing.EOTable._EOTableColumn;
import com.webobjects.foundation.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.table.*;
import javax.swing.text.*;

public class _ServerSelector_EOArchive extends com.webobjects.eoapplication.EOArchive {
    com.webobjects.eointerface.swing.EOFrame _eoFrame0;
    com.webobjects.eointerface.swing.EOTable _nsTableView0;
    com.webobjects.eointerface.swing.EOTable._EOTableColumn _eoTableColumn0;
    com.webobjects.eointerface.swing.EOTextField _nsTextField0, _nsTextField1, _nsTextField10, _nsTextField11, _nsTextField2, _nsTextField3, _nsTextField4, _nsTextField5, _nsTextField6, _nsTextField7, _nsTextField8, _nsTextField9;
    com.webobjects.eointerface.swing.EOView _nsBox0, _nsBox1, _nsView0, _nsView1, _nsView2;
    javax.swing.JButton _nsButton0, _nsButton1, _nsButton2, _nsButton3, _nsButton4;
    javax.swing.JPanel _nsView3;
    javax.swing.JTabbedPane _nsTabView0;

    public _ServerSelector_EOArchive(Object owner, NSDisposableRegistry registry) {
        super(owner, registry);
    }

    protected void _construct() {
        Object owner = _owner();
        EOArchive._ObjectInstantiationDelegate delegate = (owner instanceof EOArchive._ObjectInstantiationDelegate) ? (EOArchive._ObjectInstantiationDelegate)owner : null;
        Object replacement;

        super._construct();

        _nsView2 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _nsView1 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");
        _nsBox1 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");
        _nsBox0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSBox1");
        _nsTextField11 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField241");
        _nsTextField10 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField24");
        _nsTextField9 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField23");
        _nsTextField8 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField22");
        _nsTextField7 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField21");
        _nsTextField6 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField2");
        _nsButton4 = (javax.swing.JButton)_registered(new javax.swing.JButton("set as defaults"), "NSButton2");
        _nsButton3 = (javax.swing.JButton)_registered(new javax.swing.JButton("select"), "NSButton");
        _nsButton2 = (javax.swing.JButton)_registered(new javax.swing.JButton("abort"), "NSButton1");
        _nsButton1 = (javax.swing.JButton)_registered(new javax.swing.JButton("-"), "");
        _nsButton0 = (javax.swing.JButton)_registered(new javax.swing.JButton("+"), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "serverUserName")) != null)) {
            _nsTextField5 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField5");
        } else {
            _nsTextField5 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField3");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "serverPort")) != null)) {
            _nsTextField4 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField4");
        } else {
            _nsTextField4 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField4");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "serverName")) != null)) {
            _nsTextField3 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField3");
        } else {
            _nsTextField3 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField6");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "serverPassword")) != null)) {
            _nsTextField2 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField2");
        } else {
            _nsTextField2 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "serverInitialization")) != null)) {
            _nsTextField1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField1");
        } else {
            _nsTextField1 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "serverAddress")) != null)) {
            _nsTextField0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField0");
        } else {
            _nsTextField0 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField5");
        }

        _eoTableColumn0 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "NSTableColumn");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "serverList")) != null)) {
            _nsTableView0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTable)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTableView0");
        } else {
            _nsTableView0 = (com.webobjects.eointerface.swing.EOTable)_registered(new com.webobjects.eointerface.swing.EOTable(), "NSTableView");
        }

        _nsView0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");
        _nsTabView0 = (javax.swing.JTabbedPane)_registered(new javax.swing.JTabbedPane(), "NSTabView");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "window")) != null)) {
            _eoFrame0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOFrame)replacement;
            _replacedObjects.setObjectForKey(replacement, "_eoFrame0");
        } else {
            _eoFrame0 = (com.webobjects.eointerface.swing.EOFrame)_registered(new com.webobjects.eointerface.swing.EOFrame(), "ServerSelector");
        }

        _nsView3 = (JPanel)_eoFrame0.getContentPane();
    }

    protected void _awaken() {
        super._awaken();
        _nsButton4.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "updateDefaults", _nsButton4), ""));
        _nsButton3.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "buttonSelect", _nsButton3), ""));
        _nsButton2.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "buttonCancel", _nsButton2), ""));

        if (_replacedObjects.objectForKey("_nsTableView0") == null) {
            _connect(_nsTableView0, _owner(), "delegate");
        }

        _nsButton1.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "userDeleteCurrentServer", _nsButton1), ""));
        _nsButton0.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "userAddNewServer", _nsButton0), ""));

        if (_replacedObjects.objectForKey("_eoFrame0") == null) {
            _connect(_owner(), _eoFrame0, "window");
        }

        if (_replacedObjects.objectForKey("_nsTextField5") == null) {
            _connect(_owner(), _nsTextField5, "serverUserName");
        }

        if (_replacedObjects.objectForKey("_nsTextField4") == null) {
            _connect(_owner(), _nsTextField4, "serverPort");
        }

        if (_replacedObjects.objectForKey("_nsTableView0") == null) {
            _connect(_owner(), _nsTableView0, "serverList");
        }

        if (_replacedObjects.objectForKey("_nsTextField3") == null) {
            _connect(_owner(), _nsTextField3, "serverName");
        }

        if (_replacedObjects.objectForKey("_nsTextField2") == null) {
            _connect(_owner(), _nsTextField2, "serverPassword");
        }

        if (_replacedObjects.objectForKey("_nsTextField1") == null) {
            _connect(_owner(), _nsTextField1, "serverInitialization");
        }

        if (_replacedObjects.objectForKey("_nsTextField0") == null) {
            _connect(_owner(), _nsTextField0, "serverAddress");
        }

        if (_replacedObjects.objectForKey("_nsTableView0") == null) {
            _connect(_nsTableView0, _owner(), "dataSource");
        }
    }

    protected void _init() {
        super._init();
        if (!(_nsBox0.getLayout() instanceof EOViewLayout)) { _nsBox0.setLayout(new EOViewLayout()); }
        _nsBox1.setSize(125, 1);
        _nsBox1.setLocation(2, 2);
        ((EOViewLayout)_nsBox0.getLayout()).setAutosizingMask(_nsBox1, EOViewLayout.MinYMargin);
        _nsBox0.add(_nsBox1);
        _nsBox0.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("", true, "Lucida Grande", 13, Font.PLAIN));
        _setFontForComponent(_nsTextField11, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField11.setEditable(false);
        _nsTextField11.setOpaque(false);
        _nsTextField11.setText("Initialization:\n");
        _nsTextField11.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField11.setSelectable(false);
        _nsTextField11.setEnabled(true);
        _nsTextField11.setBorder(null);
        _setFontForComponent(_nsTextField10, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField10.setEditable(false);
        _nsTextField10.setOpaque(false);
        _nsTextField10.setText("Password:\n\n::");
        _nsTextField10.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField10.setSelectable(false);
        _nsTextField10.setEnabled(true);
        _nsTextField10.setBorder(null);
        _setFontForComponent(_nsTextField9, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField9.setEditable(false);
        _nsTextField9.setOpaque(false);
        _nsTextField9.setText("Username:");
        _nsTextField9.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField9.setSelectable(false);
        _nsTextField9.setEnabled(true);
        _nsTextField9.setBorder(null);
        _setFontForComponent(_nsTextField8, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField8.setEditable(false);
        _nsTextField8.setOpaque(false);
        _nsTextField8.setText("Port:");
        _nsTextField8.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField8.setSelectable(false);
        _nsTextField8.setEnabled(true);
        _nsTextField8.setBorder(null);
        _setFontForComponent(_nsTextField7, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField7.setEditable(false);
        _nsTextField7.setOpaque(false);
        _nsTextField7.setText("Address:");
        _nsTextField7.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField7.setSelectable(false);
        _nsTextField7.setEnabled(true);
        _nsTextField7.setBorder(null);
        _setFontForComponent(_nsTextField6, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField6.setEditable(false);
        _nsTextField6.setOpaque(false);
        _nsTextField6.setText("Name:");
        _nsTextField6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField6.setSelectable(false);
        _nsTextField6.setEnabled(true);
        _nsTextField6.setBorder(null);
        _setFontForComponent(_nsButton4, "Lucida Grande", 13, Font.PLAIN);
        _nsButton4.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_nsButton3, "Lucida Grande", 13, Font.PLAIN);
        _nsButton3.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_nsButton2, "Lucida Grande", 13, Font.PLAIN);
        _nsButton2.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_nsButton1, "Lucida Grande", 13, Font.PLAIN);
        _nsButton1.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_nsButton0, "Lucida Grande", 13, Font.PLAIN);
        _nsButton0.setMargin(new Insets(0, 2, 0, 2));

        if (_replacedObjects.objectForKey("_nsTextField5") == null) {
            _setFontForComponent(_nsTextField5, "Lucida Grande", 13, Font.PLAIN);
            _nsTextField5.setEditable(true);
            _nsTextField5.setOpaque(true);
            _nsTextField5.setText("");
            _nsTextField5.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField5.setSelectable(true);
            _nsTextField5.setEnabled(true);
        }

        if (_replacedObjects.objectForKey("_nsTextField4") == null) {
            _setFontForComponent(_nsTextField4, "Lucida Grande", 13, Font.PLAIN);
            _nsTextField4.setEditable(true);
            _nsTextField4.setOpaque(true);
            _nsTextField4.setText("");
            _nsTextField4.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField4.setSelectable(true);
            _nsTextField4.setEnabled(true);
        }

        if (_replacedObjects.objectForKey("_nsTextField3") == null) {
            _setFontForComponent(_nsTextField3, "Lucida Grande", 13, Font.PLAIN);
            _nsTextField3.setEditable(true);
            _nsTextField3.setOpaque(true);
            _nsTextField3.setText("");
            _nsTextField3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField3.setSelectable(true);
            _nsTextField3.setEnabled(true);
        }

        if (_replacedObjects.objectForKey("_nsTextField2") == null) {
            _setFontForComponent(_nsTextField2, "Lucida Grande", 13, Font.PLAIN);
            _nsTextField2.setEditable(true);
            _nsTextField2.setOpaque(true);
            _nsTextField2.setText("");
            _nsTextField2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField2.setSelectable(true);
            _nsTextField2.setEnabled(true);
        }

        if (_replacedObjects.objectForKey("_nsTextField1") == null) {
            _setFontForComponent(_nsTextField1, "Lucida Grande", 13, Font.PLAIN);
            _nsTextField1.setEditable(true);
            _nsTextField1.setOpaque(true);
            _nsTextField1.setText("");
            _nsTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField1.setSelectable(true);
            _nsTextField1.setEnabled(true);
        }

        if (_replacedObjects.objectForKey("_nsTextField0") == null) {
            _setFontForComponent(_nsTextField0, "Lucida Grande", 13, Font.PLAIN);
            _nsTextField0.setEditable(true);
            _nsTextField0.setOpaque(true);
            _nsTextField0.setText("");
            _nsTextField0.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField0.setSelectable(true);
            _nsTextField0.setEnabled(true);
        }

        _eoTableColumn0.setMinWidth(40);
        _eoTableColumn0.setMaxWidth(1000);
        _eoTableColumn0.setPreferredWidth(405);
        _eoTableColumn0.setWidth(405);
        _eoTableColumn0.setResizable(true);
        _eoTableColumn0.setHeaderValue("Name");
        if ((_eoTableColumn0.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn0.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }

        if (_replacedObjects.objectForKey("_nsTableView0") == null) {
            _nsTableView0.table().addColumn(_eoTableColumn0);
            _setFontForComponent(_nsTableView0.table().getTableHeader(), "Lucida Grande", 11, Font.PLAIN);
            _nsTableView0.table().setRowHeight(20);
        }

        if (!(_nsView0.getLayout() instanceof EOViewLayout)) { _nsView0.setLayout(new EOViewLayout()); }
        _nsTableView0.setSize(425, 169);
        _nsTableView0.setLocation(20, 0);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTableView0, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
        _nsView0.add(_nsTableView0);
        _nsTextField6.setSize(114, 17);
        _nsTextField6.setLocation(18, 221);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField6, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField6);
        _nsTextField7.setSize(114, 17);
        _nsTextField7.setLocation(18, 253);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField7, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField7);
        _nsTextField8.setSize(34, 17);
        _nsTextField8.setLocation(341, 253);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField8, EOViewLayout.MinXMargin | EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField8);
        _nsTextField9.setSize(114, 17);
        _nsTextField9.setLocation(18, 285);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField9, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField9);
        _nsTextField10.setSize(114, 17);
        _nsTextField10.setLocation(18, 317);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField10, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField10);
        _nsTextField2.setSize(309, 22);
        _nsTextField2.setLocation(137, 314);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField2, EOViewLayout.WidthSizable | EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField2);
        _nsTextField5.setSize(309, 22);
        _nsTextField5.setLocation(137, 282);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField5, EOViewLayout.WidthSizable | EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField5);
        _nsTextField4.setSize(66, 22);
        _nsTextField4.setLocation(380, 250);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField4, EOViewLayout.MinXMargin | EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField4);
        _nsTextField0.setSize(199, 22);
        _nsTextField0.setLocation(137, 250);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField0, EOViewLayout.WidthSizable | EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField0);
        _nsTextField3.setSize(309, 22);
        _nsTextField3.setLocation(137, 218);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField3, EOViewLayout.WidthSizable | EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField3);
        _nsTextField11.setSize(114, 17);
        _nsTextField11.setLocation(18, 349);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField11, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField11);
        _nsButton1.setSize(31, 26);
        _nsButton1.setLocation(414, 176);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsButton1, EOViewLayout.MinXMargin | EOViewLayout.MinYMargin);
        _nsView0.add(_nsButton1);
        _nsButton0.setSize(31, 26);
        _nsButton0.setLocation(379, 176);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsButton0, EOViewLayout.MinXMargin | EOViewLayout.MinYMargin);
        _nsView0.add(_nsButton0);
        _nsBox0.setSize(425, 5);
        _nsBox0.setLocation(20, 207);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsBox0, EOViewLayout.WidthSizable | EOViewLayout.MinYMargin);
        _nsView0.add(_nsBox0);
        _nsTextField1.setSize(309, 56);
        _nsTextField1.setLocation(137, 346);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField1, EOViewLayout.WidthSizable | EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField1);
        _nsTabView0.addTab("Server", _nsView0);
        _nsTabView0.addTab("Programm", _nsView1);
        _nsTabView0.addTab("Analysis", _nsView2);
        if (!(_nsView3.getLayout() instanceof EOViewLayout)) { _nsView3.setLayout(new EOViewLayout()); }
        _nsTabView0.setSize(475, 448);
        _nsTabView0.setLocation(11, 3);
        ((EOViewLayout)_nsView3.getLayout()).setAutosizingMask(_nsTabView0, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
        _nsView3.add(_nsTabView0);
        _nsButton3.setSize(75, 26);
        _nsButton3.setLocation(413, 452);
        ((EOViewLayout)_nsView3.getLayout()).setAutosizingMask(_nsButton3, EOViewLayout.MinXMargin | EOViewLayout.MinYMargin);
        _nsView3.add(_nsButton3);
        _nsButton2.setSize(75, 26);
        _nsButton2.setLocation(331, 452);
        ((EOViewLayout)_nsView3.getLayout()).setAutosizingMask(_nsButton2, EOViewLayout.MinXMargin | EOViewLayout.MinYMargin);
        _nsView3.add(_nsButton2);
        _nsButton4.setSize(125, 26);
        _nsButton4.setLocation(12, 452);
        ((EOViewLayout)_nsView3.getLayout()).setAutosizingMask(_nsButton4, EOViewLayout.MaxXMargin | EOViewLayout.MinYMargin);
        _nsView3.add(_nsButton4);

        if (_replacedObjects.objectForKey("_eoFrame0") == null) {
            _nsView3.setSize(497, 488);
            _eoFrame0.setTitle("Select Chess Server");
            _eoFrame0.setLocation(577, -37);
            _eoFrame0.setSize(497, 488);
        }
    }
}
