// _GameWindow_EOArchive.java
// Generated by EnterpriseObjects palette at Sunday, November 27, 2005 4:05:00 PM Asia/Taipei

import com.webobjects.eoapplication.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eointerface.*;
import com.webobjects.eointerface.swing.*;
import com.webobjects.eointerface.swing.EOTable._EOTableColumn;
import com.webobjects.foundation.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.table.*;
import javax.swing.text.*;

public class _GameWindow_EOArchive extends com.webobjects.eoapplication.EOArchive {
    ChessView _nsCustomView0;
    com.webobjects.eointerface.swing.EOFrame _eoFrame0, _eoFrame1;
    com.webobjects.eointerface.swing.EOTable _nsTableView0;
    com.webobjects.eointerface.swing.EOTable._EOTableColumn _eoTableColumn0, _eoTableColumn1, _eoTableColumn2;
    com.webobjects.eointerface.swing.EOTextArea _nsTextView0;
    com.webobjects.eointerface.swing.EOTextField _nsTextField0, _nsTextField1, _nsTextField2, _nsTextField3;
    javax.swing.JButton _nsButton0, _nsButton1, _nsButton2, _nsButton3, _nsButton4, _nsButton5, _nsButton6, _nsButton7, _nsButton8;
    javax.swing.JPanel _nsView0, _nsView1;

    public _GameWindow_EOArchive(Object owner, NSDisposableRegistry registry) {
        super(owner, registry);
    }

    protected void _construct() {
        Object owner = _owner();
        EOArchive._ObjectInstantiationDelegate delegate = (owner instanceof EOArchive._ObjectInstantiationDelegate) ? (EOArchive._ObjectInstantiationDelegate)owner : null;
        Object replacement;

        super._construct();

        _nsButton8 = (javax.swing.JButton)_registered(new javax.swing.JButton("Seek"), "");
        _eoTableColumn2 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn1 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "NSTableColumn1");
        _eoTableColumn0 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "NSTableColumn");
        _nsTableView0 = (com.webobjects.eointerface.swing.EOTable)_registered(new com.webobjects.eointerface.swing.EOTable(), "NSTableView");
        _nsTextField3 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField11");
        _nsTextField2 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1");
        _nsCustomView0 = (ChessView)_registered(new ChessView(), "View");
        _nsButton7 = (javax.swing.JButton)_registered(new javax.swing.JButton("end"), "");
        _nsButton6 = (javax.swing.JButton)_registered(new javax.swing.JButton("next"), "");
        _nsButton5 = (javax.swing.JButton)_registered(new javax.swing.JButton("pre"), "");
        _nsButton4 = (javax.swing.JButton)_registered(new javax.swing.JButton("start"), "");
        _eoFrame1 = (com.webobjects.eointerface.swing.EOFrame)_registered(new com.webobjects.eointerface.swing.EOFrame(), "GameWindow");
        _nsView1 = (JPanel)_eoFrame1.getContentPane();

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "serverInput")) != null)) {
            _nsTextField1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField1");
        } else {
            _nsTextField1 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "serverOutput")) != null)) {
            _nsTextView0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextArea)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextView0");
        } else {
            _nsTextView0 = (com.webobjects.eointerface.swing.EOTextArea)_registered(new com.webobjects.eointerface.swing.EOTextArea(), "NSTextView");
        }

        _nsButton3 = (javax.swing.JButton)_registered(new javax.swing.JButton(""), "");
        _nsButton2 = (javax.swing.JButton)_registered(new javax.swing.JButton(""), "");
        _nsButton1 = (javax.swing.JButton)_registered(new javax.swing.JButton(""), "");
        _nsButton0 = (javax.swing.JButton)_registered(new javax.swing.JButton(""), "");
        _nsTextField0 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField2");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "promotionPiece")) != null)) {
            _eoFrame0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOFrame)replacement;
            _replacedObjects.setObjectForKey(replacement, "_eoFrame0");
        } else {
            _eoFrame0 = (com.webobjects.eointerface.swing.EOFrame)_registered(new com.webobjects.eointerface.swing.EOFrame(), "PromotionPiece");
        }

        _nsView0 = (JPanel)_eoFrame0.getContentPane();
    }

    protected void _awaken() {
        super._awaken();

        if (_replacedObjects.objectForKey("_nsTextField1") == null) {
            _connect(_owner(), _nsTextField1, "serverInput");
        }

        if (_replacedObjects.objectForKey("_nsTextView0") == null) {
            _connect(_owner(), _nsTextView0, "serverOutput");
        }

        if (_replacedObjects.objectForKey("_eoFrame0") == null) {
            _connect(_owner(), _eoFrame0, "promotionPiece");
        }
    }

    protected void _init() {
        super._init();
        _setFontForComponent(_nsButton8, "Lucida Grande", 13, Font.PLAIN);
        _nsButton8.setMargin(new Insets(0, 2, 0, 2));
        _eoTableColumn2.setMinWidth(35);
        _eoTableColumn2.setMaxWidth(1000);
        _eoTableColumn2.setPreferredWidth(70);
        _eoTableColumn2.setWidth(70);
        _eoTableColumn2.setResizable(false);
        _eoTableColumn2.setHeaderValue("Black");
        if ((_eoTableColumn2.getCellRenderer() instanceof DefaultTableCellRenderer) || (_eoTableColumn2.getCellRenderer() == null)) {
        	DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        	renderer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        	_eoTableColumn2.setCellRenderer(renderer);
        }
        _eoTableColumn1.setMinWidth(40);
        _eoTableColumn1.setMaxWidth(1000);
        _eoTableColumn1.setPreferredWidth(69);
        _eoTableColumn1.setWidth(69);
        _eoTableColumn1.setResizable(false);
        _eoTableColumn1.setHeaderValue("White");
        if ((_eoTableColumn1.getCellRenderer() instanceof DefaultTableCellRenderer) || (_eoTableColumn1.getCellRenderer() == null)) {
        	DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        	renderer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        	_eoTableColumn1.setCellRenderer(renderer);
        }
        _eoTableColumn0.setMinWidth(40);
        _eoTableColumn0.setMaxWidth(1000);
        _eoTableColumn0.setPreferredWidth(40);
        _eoTableColumn0.setWidth(40);
        _eoTableColumn0.setResizable(false);
        _eoTableColumn0.setHeaderValue("Move");
        if ((_eoTableColumn0.getCellRenderer() instanceof DefaultTableCellRenderer) || (_eoTableColumn0.getCellRenderer() == null)) {
        	DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        	renderer.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        	_eoTableColumn0.setCellRenderer(renderer);
        }
        if ((_eoTableColumn0.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn0.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        }
        _nsTableView0.table().addColumn(_eoTableColumn0);
        _nsTableView0.table().addColumn(_eoTableColumn1);
        _nsTableView0.table().addColumn(_eoTableColumn2);
        _setFontForComponent(_nsTableView0.table().getTableHeader(), "Lucida Grande", 11, Font.PLAIN);
        _nsTableView0.table().setRowHeight(20);
        _setFontForComponent(_nsTextField3, "Monaco", 36, Font.PLAIN);
        _nsTextField3.setEditable(false);
        _nsTextField3.setOpaque(true);
        _nsTextField3.setText("9:99:99.9");
        _nsTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        _nsTextField3.setSelectable(false);
        _nsTextField3.setEnabled(true);
        _nsTextField3.setBorder(new LineBorder(Color.black));
        _setFontForComponent(_nsTextField2, "Monaco", 36, Font.PLAIN);
        _nsTextField2.setEditable(false);
        _nsTextField2.setOpaque(true);
        _nsTextField2.setText("9:99:99.9");
        _nsTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        _nsTextField2.setSelectable(false);
        _nsTextField2.setEnabled(true);
        _nsTextField2.setBorder(new LineBorder(Color.black));
        _setFontForComponent(_nsButton7, "Lucida Grande", 13, Font.PLAIN);
        _nsButton7.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_nsButton6, "Lucida Grande", 13, Font.PLAIN);
        _nsButton6.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_nsButton5, "Lucida Grande", 13, Font.PLAIN);
        _nsButton5.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_nsButton4, "Lucida Grande", 13, Font.PLAIN);
        _nsButton4.setMargin(new Insets(0, 2, 0, 2));
        if (!(_nsView1.getLayout() instanceof EOViewLayout)) { _nsView1.setLayout(new EOViewLayout()); }
        _nsButton4.setSize(37, 33);
        _nsButton4.setLocation(799, 70);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsButton4, EOViewLayout.MinXMargin | EOViewLayout.MaxYMargin);
        _nsView1.add(_nsButton4);
        _nsButton5.setSize(37, 34);
        _nsButton5.setLocation(799, 109);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsButton5, EOViewLayout.MinXMargin | EOViewLayout.MaxYMargin);
        _nsView1.add(_nsButton5);
        _nsButton6.setSize(37, 33);
        _nsButton6.setLocation(799, 445);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsButton6, EOViewLayout.MinXMargin | EOViewLayout.MinYMargin);
        _nsView1.add(_nsButton6);
        _nsButton7.setSize(37, 34);
        _nsButton7.setLocation(799, 484);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsButton7, EOViewLayout.MinXMargin | EOViewLayout.MinYMargin);
        _nsView1.add(_nsButton7);
        _nsCustomView0.setSize(560, 560);
        _nsCustomView0.setLocation(13, 14);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsCustomView0, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
        _nsView1.add(_nsCustomView0);
        _nsTextField2.setSize(251, 49);
        _nsTextField2.setLocation(586, 14);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsTextField2, EOViewLayout.MinXMargin | EOViewLayout.MaxYMargin);
        _nsView1.add(_nsTextField2);
        _nsTextField3.setSize(251, 49);
        _nsTextField3.setLocation(586, 525);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsTextField3, EOViewLayout.MinXMargin | EOViewLayout.MinYMargin);
        _nsView1.add(_nsTextField3);
        _nsTableView0.setSize(206, 446);
        _nsTableView0.setLocation(585, 71);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsTableView0, EOViewLayout.MinXMargin | EOViewLayout.HeightSizable);
        _nsView1.add(_nsTableView0);
        _nsTextView0.setSize(823, 123);
        _nsTextView0.setLocation(13, 582);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsTextView0, EOViewLayout.WidthSizable | EOViewLayout.MinYMargin);
        _nsView1.add(_nsTextView0);
        _nsTextField1.setSize(778, 27);
        _nsTextField1.setLocation(14, 713);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsTextField1, EOViewLayout.WidthSizable | EOViewLayout.MinYMargin);
        _nsView1.add(_nsTextField1);
        _nsButton8.setSize(38, 28);
        _nsButton8.setLocation(798, 712);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsButton8, EOViewLayout.MinXMargin | EOViewLayout.MinYMargin);
        _nsView1.add(_nsButton8);
        _nsView1.setSize(849, 754);
        _eoFrame1.setTitle("Window");
        _eoFrame1.setLocation(574, 96);
        _eoFrame1.setSize(849, 754);

        if (_replacedObjects.objectForKey("_nsTextField1") == null) {
            _setFontForComponent(_nsTextField1, "Lucida Grande", 13, Font.PLAIN);
            _nsTextField1.setEditable(true);
            _nsTextField1.setOpaque(true);
            _nsTextField1.setText("");
            _nsTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField1.setSelectable(true);
            _nsTextField1.setEnabled(true);
        }

        if (_replacedObjects.objectForKey("_nsTextView0") == null) {
            _nsTextView0.setEditable(false);
            _nsTextView0.setOpaque(true);
            _nsTextView0.setText(" \n");
            _setFontForComponent(_nsTextView0.textArea(), "Courier", 12, Font.PLAIN);
        }

        _setFontForComponent(_nsButton3, "Lucida Grande", 10, Font.PLAIN);
        _nsButton3.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_nsButton2, "Lucida Grande", 10, Font.PLAIN);
        _nsButton2.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_nsButton1, "Lucida Grande", 10, Font.PLAIN);
        _nsButton1.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_nsButton0, "Lucida Grande", 10, Font.PLAIN);
        _nsButton0.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_nsTextField0, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField0.setEditable(false);
        _nsTextField0.setOpaque(false);
        _nsTextField0.setText("Promote to:\n");
        _nsTextField0.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField0.setSelectable(false);
        _nsTextField0.setEnabled(true);
        _nsTextField0.setBorder(null);
        if (!(_nsView0.getLayout() instanceof EOViewLayout)) { _nsView0.setLayout(new EOViewLayout()); }
        _nsTextField0.setSize(386, 20);
        _nsTextField0.setLocation(11, 14);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField0, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField0);
        _nsButton0.setSize(139, 129);
        _nsButton0.setLocation(11, 41);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsButton0, EOViewLayout.MinYMargin);
        _nsView0.add(_nsButton0);
        _nsButton1.setSize(139, 129);
        _nsButton1.setLocation(440, 41);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsButton1, EOViewLayout.MinYMargin);
        _nsView0.add(_nsButton1);
        _nsButton2.setSize(139, 129);
        _nsButton2.setLocation(297, 41);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsButton2, EOViewLayout.MinYMargin);
        _nsView0.add(_nsButton2);
        _nsButton3.setSize(139, 129);
        _nsButton3.setLocation(154, 41);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsButton3, EOViewLayout.MinYMargin);
        _nsView0.add(_nsButton3);

        if (_replacedObjects.objectForKey("_eoFrame0") == null) {
            _nsView0.setSize(590, 180);
            _eoFrame0.setTitle("Choose promotion piece");
            _eoFrame0.setLocation(126, 561);
            _eoFrame0.setSize(590, 180);
        }
    }
}
